apiVersion: v1
kind: Service
metadata:
  name: {{ include "simpletimeservice.fullname" . }}
  labels:
    {{- include "simpletimeservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "simpletimeservice.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    protocol: TCP
  sessionAffinity: None

