apiVersion: v1
kind: Namespace
metadata:
  name: simpletimeservice
  labels:
    name: simpletimeservice
    environment: production
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

