apiVersion: v1
kind: ServiceAccount
metadata:
  name: simpletimeservice
  namespace: simpletimeservice
  labels:
    app: simpletimeservice
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::<ACCOUNT_ID>:role/simpletimeservice-app"

