apiVersion: v2
name: simpletimeservice
description: A Helm chart for SimpleTimeService microservice
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - microservice
  - time
  - ip
home: https://github.com/particle41/simpletimeservice
maintainers:
  - name: DevOps Team
    email: careers@particle41.com

